version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - server
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_URL=http://localhost:3001

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - PORT=3001
      - NODE_ENV=production
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=104857600
      - PROTOTYPE_MODE=${PROTOTYPE_MODE:-false}
      - DEV_BYPASS_AUTH=${DEV_BYPASS_AUTH:-false}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3002}

volumes:
  uploads: