[build]
  base = "./"
  command = "npm run build"
  publish = "client/build"

# Development settings
[dev]
  framework = "create-react-app"
  command = "npm run dev"
  port = 8888
  publish = "client/build"
  targetPort = 3000

# Environment variables
[build.environment]
  REACT_APP_SERVER_URL = "https://api-airwave.redbaez.com"
  REACT_APP_SUPABASE_URL = "https://vnlmumkhqupdmvywneuf.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubG11bWtocXVwZG12eXduZXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMzQ2MjEsImV4cCI6MjA1NjcxMDYyMX0.rGn9_Zkbb0FYXwjs-RLlWO6lpqoTbQRsNFwmvdn1pDQ"
  REACT_APP_CREATOMATE_PUBLIC_TOKEN = "public-b66aek9a6jsq2sff011uytlh"
  NODE_ENV = "production"

# Production context
[context.production]
  command = "npm run build"

# Branch specific settings
[context.develop]
  command = "npm run build"
  # Different API URL for develop branch
  environment = { REACT_APP_API_URL = "https://api-dev-airwave.redbaez.com" }

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# More specific redirects
[[redirects]]
  from = "/api/*"
  to = "https://api-airwave.redbaez.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

# WebSocket handling
[[redirects]]
  from = "/ws/*"
  to = "wss://api-airwave.redbaez.com/ws/:splat"
  status = 101
  force = true