name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd client && npm ci
        cd ../server && npm ci
    
    - name: Build
      run: |
        cd client && npm run build
        cd ../server && npm run build
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push client
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: airwaveredbaez/client:latest
    
    - name: Build and push server
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: true
        tags: airwaveredbaez/server:latest
        
    - name: Deploy to production
      run: |
        echo "Deploying to production environment"
        # Add deployment scripts here
        # This could be kubectl commands, SSH to server, etc.
